# Run once from the Main Tori repository root, with the bot stopped.
# Requires Docker Desktop and data/mongo-import generated by export-legacy.py.
$ErrorActionPreference = 'Stop'
$root = (Resolve-Path (Join-Path $PSScriptRoot '../..')).Path
$source = Join-Path $root 'data/mongo-import'
$manifestPath = Join-Path $source 'manifest.json'
if (-not (Test-Path -LiteralPath $manifestPath)) { throw 'Run export-legacy.py first.' }
$manifest = Get-Content -LiteralPath $manifestPath -Raw | ConvertFrom-Json
$docker = (Get-Command docker.exe -ErrorAction SilentlyContinue).Source
if (-not $docker) { $docker = Join-Path $env:LOCALAPPDATA 'Programs/DockerDesktop/resources/bin/docker.exe' }
if (-not (Test-Path -LiteralPath $docker)) { throw 'Docker CLI not found.' }
Push-Location $root
try {
    $container = (& $docker compose ps -q mongodb).Trim()
    if ($LASTEXITCODE -ne 0 -or -not $container) { throw 'Start the MongoDB service with docker compose up -d mongodb first.' }
    $check = 'mongosh --quiet --username tori --password "$MONGO_INITDB_ROOT_PASSWORD" --authenticationDatabase admin tori_main --eval ''db.getCollectionNames().some(n => db.getCollection(n).estimatedDocumentCount() > 0)'''
    $occupied = (& $docker exec $container sh -c $check).Trim()
    if ($LASTEXITCODE -ne 0) { throw 'MongoDB could not be queried.' }
    if ($occupied -ne 'false') { throw 'Target database contains data. Import stopped to prevent overwriting it.' }
    foreach ($name in @('bot_stats_context', 'bot_events', 'guild_prefixes', 'moderation_cases', 'guild_languages')) {
        $file = Join-Path $source "$name.jsonl"
        if (-not (Test-Path -LiteralPath $file)) { throw "Missing export file: $name" }
        if ($manifest.$name -eq 0) { continue }
        & $docker cp $file "${container}:/tmp/tori-$name.jsonl"
        if ($LASTEXITCODE -ne 0) { throw "Copy failed: $name" }
        $command = "mongoimport --quiet --username tori --password " + '"$MONGO_INITDB_ROOT_PASSWORD"' +
            " --authenticationDatabase admin --db tori_main --collection $name --type json --file /tmp/tori-$name.jsonl --mode insert --stopOnError"
        & $docker exec $container sh -c $command
        if ($LASTEXITCODE -ne 0) { throw "Import failed: $name. Inspect the partial target before retrying." }
        & $docker exec $container rm "/tmp/tori-$name.jsonl" | Out-Null
    }
    foreach ($name in @('bot_stats_context', 'bot_events', 'guild_prefixes', 'moderation_cases', 'guild_languages')) {
        $query = "mongosh --quiet --username tori --password " + '"$MONGO_INITDB_ROOT_PASSWORD"' +
            " --authenticationDatabase admin tori_main --eval 'db.$name.countDocuments({})'"
        $result = & $docker exec $container sh -c $query
        $actual = if ($null -eq $result) { '' } else { ($result | Out-String).Trim() }
        if ($LASTEXITCODE -ne 0 -or $actual -ne [string]$manifest.$name) {
            throw "Count mismatch for $name; expected $($manifest.$name), got $actual."
        }
    }
    Write-Output 'MongoDB import verified. The SQLite snapshot remains unchanged under data/mongo-import.'
} finally { Pop-Location }
