CREATE TABLE bot_stats_context (
    bot_id TEXT NOT NULL, guild_id TEXT NOT NULL, channel_id TEXT NOT NULL,
    guild_name TEXT NOT NULL, channel_name TEXT NOT NULL, updated_at TIMESTAMPTZ NOT NULL,
    schema_version INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (bot_id, guild_id, channel_id)
);

CREATE TABLE bot_events (
    session_id TEXT NOT NULL, event_type TEXT NOT NULL CHECK (event_type IN ('BOT_STARTED', 'BOT_STOPPED')),
    reason TEXT, occurred_at TIMESTAMPTZ NOT NULL, started_at TIMESTAMPTZ NOT NULL,
    schema_version INTEGER NOT NULL DEFAULT 1, PRIMARY KEY (session_id, event_type)
);
CREATE INDEX bot_events_type_time_idx ON bot_events(event_type, occurred_at DESC);

CREATE TABLE guild_prefixes (guild_id TEXT PRIMARY KEY, prefix TEXT NOT NULL, schema_version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE guild_languages (
    guild_id TEXT PRIMARY KEY, language TEXT NOT NULL CHECK (language IN ('de', 'en', 'nl')),
    schema_version INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE moderation_cases (
    guild_id TEXT NOT NULL, case_id TEXT NOT NULL, action TEXT NOT NULL, guild_name TEXT, channel_id TEXT,
    moderator_id TEXT, moderator_name TEXT, target TEXT, reason TEXT, result TEXT,
    occurred_at TIMESTAMPTZ NOT NULL, language TEXT NOT NULL CHECK (language IN ('de', 'en', 'nl')),
    webhook_status TEXT NOT NULL, webhook_attempts INTEGER NOT NULL DEFAULT 0 CHECK (webhook_attempts >= 0),
    webhook_http_status INTEGER, webhook_error TEXT, webhook_updated_at TIMESTAMPTZ NOT NULL,
    schema_version INTEGER NOT NULL DEFAULT 1, PRIMARY KEY (guild_id, case_id)
);
CREATE INDEX moderation_cases_guild_time_idx ON moderation_cases(guild_id, occurred_at DESC);

CREATE TABLE guild_ticket_order_config (
    guild_id TEXT PRIMARY KEY, order_staff_role_id TEXT, order_channel_id TEXT, ticket_category_id TEXT,
    ticket_panel_channel_id TEXT, queue_mode TEXT NOT NULL DEFAULT 'SEQUENTIAL' CHECK (queue_mode IN ('SEQUENTIAL', 'PARALLEL')),
    ticket_staff_role_id TEXT, ticket_panel_title TEXT, ticket_panel_body TEXT, ticket_button_label TEXT,
    ticket_welcome_body TEXT, ticket_claim_label TEXT, ticket_close_label TEXT, ticket_delete_label TEXT,
    schema_version INTEGER NOT NULL DEFAULT 1
);
CREATE TABLE guild_ticket_order_counters (
    guild_id TEXT NOT NULL, counter_type TEXT NOT NULL CHECK (counter_type IN ('ticket', 'order')),
    value BIGINT NOT NULL CHECK (value >= 0), schema_version INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (guild_id, counter_type)
);

CREATE TABLE guild_orders (
    guild_id TEXT NOT NULL, order_id BIGINT NOT NULL CHECK (order_id > 0), customer_id TEXT NOT NULL,
    product TEXT NOT NULL, description TEXT NOT NULL, assigned_staff_id TEXT,
    status TEXT NOT NULL CHECK (status IN ('NOTED', 'PROCESSING', 'DONE', 'CANCELLED')),
    created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, ticket_id BIGINT,
    post_channel_id TEXT, post_message_id TEXT, schema_version INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (guild_id, order_id)
);
CREATE INDEX guild_orders_active_queue_idx ON guild_orders(guild_id, created_at, order_id)
    WHERE status NOT IN ('DONE', 'CANCELLED');
CREATE TABLE guild_order_status_events (
    guild_id TEXT NOT NULL, interaction_id TEXT NOT NULL, order_id BIGINT NOT NULL,
    previous_status TEXT NOT NULL, new_status TEXT NOT NULL, actor_id TEXT NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL, schema_version INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (guild_id, interaction_id),
    FOREIGN KEY (guild_id, order_id) REFERENCES guild_orders(guild_id, order_id) ON DELETE RESTRICT
);
CREATE INDEX guild_order_status_events_order_idx ON guild_order_status_events(guild_id, order_id, occurred_at);
CREATE TABLE guild_order_assignment_events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, guild_id TEXT NOT NULL, order_id BIGINT NOT NULL,
    actor_id TEXT NOT NULL, staff_id TEXT, occurred_at TIMESTAMPTZ NOT NULL,
    FOREIGN KEY (guild_id, order_id) REFERENCES guild_orders(guild_id, order_id) ON DELETE RESTRICT
);
CREATE INDEX guild_order_assignment_events_order_idx ON guild_order_assignment_events(guild_id, order_id, occurred_at);

CREATE TABLE guild_tickets (
    guild_id TEXT NOT NULL, ticket_id BIGINT NOT NULL CHECK (ticket_id > 0), creator_id TEXT NOT NULL,
    category TEXT NOT NULL, channel_id TEXT NOT NULL, status TEXT NOT NULL CHECK (status IN ('OPEN', 'CLOSED', 'DELETED')),
    assigned_staff_id TEXT, created_at TIMESTAMPTZ NOT NULL, closed_at TIMESTAMPTZ, deleted_at TIMESTAMPTZ,
    order_id BIGINT, schema_version INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (guild_id, ticket_id), UNIQUE (guild_id, channel_id)
);
CREATE INDEX guild_tickets_open_by_creator_idx ON guild_tickets(guild_id, creator_id, category) WHERE status = 'OPEN';
CREATE TABLE guild_ticket_members (
    guild_id TEXT NOT NULL, ticket_id BIGINT NOT NULL, member_id TEXT NOT NULL,
    PRIMARY KEY (guild_id, ticket_id, member_id),
    FOREIGN KEY (guild_id, ticket_id) REFERENCES guild_tickets(guild_id, ticket_id) ON DELETE RESTRICT
);
CREATE TABLE guild_ticket_events (
    event_key TEXT PRIMARY KEY, guild_id TEXT NOT NULL, ticket_id BIGINT NOT NULL, event_type TEXT NOT NULL,
    actor_id TEXT NOT NULL, detail TEXT NOT NULL DEFAULT '', occurred_at TIMESTAMPTZ NOT NULL,
    schema_version INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY (guild_id, ticket_id) REFERENCES guild_tickets(guild_id, ticket_id) ON DELETE RESTRICT
);
CREATE INDEX guild_ticket_events_ticket_idx ON guild_ticket_events(guild_id, ticket_id, occurred_at);
CREATE TABLE guild_ticket_transcripts (
    guild_id TEXT NOT NULL, ticket_id BIGINT NOT NULL, source_channel_id TEXT NOT NULL, archived_by TEXT NOT NULL,
    archived_at TIMESTAMPTZ NOT NULL, message_count INTEGER NOT NULL CHECK (message_count >= 0), content TEXT NOT NULL,
    schema_version INTEGER NOT NULL DEFAULT 1, PRIMARY KEY (guild_id, ticket_id),
    FOREIGN KEY (guild_id, ticket_id) REFERENCES guild_tickets(guild_id, ticket_id) ON DELETE RESTRICT
);
ALTER TABLE guild_orders ADD CONSTRAINT guild_orders_ticket_fk
    FOREIGN KEY (guild_id, ticket_id) REFERENCES guild_tickets(guild_id, ticket_id)
    ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE guild_tickets ADD CONSTRAINT guild_tickets_order_fk
    FOREIGN KEY (guild_id, order_id) REFERENCES guild_orders(guild_id, order_id)
    ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;

-- Retain imported source documents for audit/rollback; application queries use the normalized tables above.
CREATE TABLE mongo_import_archive (
    collection_name TEXT NOT NULL, document_key TEXT NOT NULL, payload JSONB NOT NULL,
    imported_at TIMESTAMPTZ NOT NULL DEFAULT now(), PRIMARY KEY (collection_name, document_key)
);
