-- Original generic Tori items. IDs never replace historical ShopCatalog or market purchases.
-- Existing catalog edits, inventory and ownership are preserved on rerun.
INSERT INTO economy_v2_catalog_items
    (item_id,name,description,category,subcategory,rarity,buy_price,rotation_weight,season,
     stackable,max_stack,consumable,equip_slots,conflict_slots,tags)
SELECT id,name,description,category,subcategory,rarity,price,weight,season,
       slot IS NULL, CASE WHEN slot IS NULL THEN 99 ELSE 1 END,
       category = 'consumables',
       CASE WHEN slot IS NULL THEN ARRAY[]::TEXT[] ELSE ARRAY[slot] END,
       CASE WHEN conflict = '' THEN ARRAY[]::TEXT[] ELSE string_to_array(conflict, ',') END,
       CASE WHEN tags = '' THEN ARRAY[]::TEXT[] ELSE string_to_array(tags, ',') END
FROM (VALUES
('leopard_baby_tee','Leopard Print Baby Tee','Soft animal-print everyday tee.','fashion','baby_tees','common',75,100,NULL,'top','dress','animal_print,y2k'),
('pink_lace_cami','Pink Lace Cami','A light cami with lace trim.','fashion','camis','common',65,100,NULL,'top','dress','lace,pink'),
('cherry_crop_top','Cherry Crop Top','A cheerful cherry-print top.','fashion','crop_tops','uncommon',90,40,NULL,'top','dress','cherries,y2k'),
('cloud_tube_top','Cloud Tube Top','Soft blue bandeau-style top.','fashion','tube_tops','common',65,90,NULL,'top','dress','summer'),
('off_shoulder_heart_top','Off-Shoulder Heart Top','A relaxed heart-print top.','fashion','off_shoulder','uncommon',100,40,NULL,'top','dress','hearts'),
('rhinestone_zip_hoodie','Rhinestone Zip Hoodie','A cozy hoodie with tiny sparkling details.','fashion','zip_hoodies','rare',210,12,NULL,'outerwear','','rhinestones,y2k'),
('pink_pullover_hoodie','Pink Pullover Hoodie','Oversized and soft.','fashion','hoodies','common',120,90,NULL,'outerwear','','pink,cozy'),
('bow_knit_cardigan','Bow Knit Cardigan','A lightweight cardigan with bow accents.','fashion','cardigans','uncommon',160,35,NULL,'outerwear','','bows,cozy'),
('cream_cable_sweater','Cream Cable Sweater','A classic cable-knit layer.','fashion','sweaters','common',130,80,NULL,'top','dress','cozy'),
('washed_denim_mini','Washed Denim Mini Skirt','Washed denim with a clean hem.','fashion','denim_skirts','common',120,90,NULL,'bottom','dress','denim,y2k'),
('pink_pleated_skirt','Pink Pleated Skirt','A playful pleated skirt.','fashion','pleated_skirts','uncommon',135,35,NULL,'bottom','dress','pink'),
('black_flared_jeans','Black Flared Jeans','A comfortable flared denim fit.','fashion','flared_jeans','common',150,90,NULL,'bottom','dress','denim,y2k'),
('stone_baggy_jeans','Stone Baggy Jeans','Relaxed washed denim.','fashion','baggy_jeans','common',150,85,NULL,'bottom','dress','denim'),
('straight_blue_jeans','Straight Blue Jeans','A reliable everyday pair.','fashion','straight_jeans','common',145,85,NULL,'bottom','dress','denim'),
('olive_cargo_pants','Olive Cargo Pants','Practical pockets and a relaxed cut.','fashion','cargo_pants','uncommon',165,35,NULL,'bottom','dress','streetwear'),
('linen_summer_shorts','Linen Summer Shorts','Lightweight warm-weather shorts.','fashion','shorts','common',95,90,'summer','bottom','dress','summer'),
('soft_pink_slip_dress','Soft Pink Slip Dress','A simple glossy evening look.','fashion','dresses','uncommon',190,30,NULL,'dress','top,bottom','pink,glam'),
('denim_cropped_jacket','Denim Cropped Jacket','A cropped washed-denim layer.','fashion','jackets','uncommon',185,35,NULL,'outerwear','','denim'),
('white_platform_sneakers','White Platform Sneakers','Everyday sneakers with a little lift.','fashion','sneakers','common',170,85,NULL,'shoes','','y2k'),
('black_ankle_boots','Black Ankle Boots','A versatile pair of ankle boots.','fashion','boots','uncommon',190,35,NULL,'shoes','','streetwear'),
('satin_sleep_set','Satin Sleep Set','A comfortable two-piece sleep set.','fashion','sleepwear','uncommon',145,30,NULL,NULL,'','cozy'),
('cherry_shoulder_bag','Cherry Shoulder Bag','A compact cherry-red shoulder bag.','accessories','shoulder_bags','uncommon',120,40,NULL,'bag','','cherries,y2k'),
('heart_pendant','Heart Pendant Necklace','A tiny heart on a fine chain.','accessories','necklaces','common',80,95,NULL,'jewelry','','hearts'),
('silver_stack_rings','Silver Stack Rings','A set of simple stacking rings.','accessories','rings','common',70,95,NULL,'jewelry','','silver'),
('pink_bead_bracelet','Pink Bead Bracelet','A colorful bracelet for everyday outfits.','accessories','bracelets','common',55,100,NULL,'jewelry','','pink'),
('star_hoop_earrings','Star Hoop Earrings','Small hoops with star charms.','accessories','earrings','uncommon',90,40,NULL,'jewelry','','stars'),
('oversized_sunglasses','Oversized Sunglasses','A bold pair for sunny days.','accessories','glasses','common',85,90,NULL,'accessory','','summer'),
('glossy_bow_clip','Glossy Bow Hair Clip','A simple glossy bow clip.','accessories','hair_clips','common',45,100,NULL,'hair_accessory','','bows'),
('zebra_print_belt','Zebra Print Belt','A playful animal-print accent.','accessories','belts','uncommon',80,35,NULL,'accessory','','animal_print'),
('mini_canvas_tote','Mini Canvas Tote','A small practical day bag.','accessories','bags','common',95,85,NULL,'bag','','casual'),
('rose_lip_gloss','Rose Lip Gloss','A rose-toned cosmetic collectible.','beauty','makeup','common',65,90,NULL,NULL,'','cosmetic,gloss'),
('peach_blush','Peach Blush','A soft blush collectible.','beauty','makeup','common',70,85,NULL,NULL,'','cosmetic'),
('shimmer_nail_set','Shimmer Nail Set','Tiny shimmering nail colors.','beauty','nails','uncommon',100,40,NULL,NULL,'','cosmetic'),
('vanilla_perfume','Vanilla Perfume','A warm scent collectible.','beauty','perfume','rare',220,12,NULL,NULL,'','cosmetic'),
('satin_hair_ribbon','Satin Hair Ribbon','A smooth hair ribbon.','beauty','hair','common',45,90,NULL,'hair_accessory','','cosmetic,bows'),
('cloud_skin_mask','Cloud Skin Mask','A single-use skincare mask.','consumables','skincare','common',35,90,NULL,NULL,'','skincare'),
('ballet_wrap_skirt','Ballet Wrap Skirt','A lightweight rehearsal wrap.','ballet','wrap_skirts','common',110,85,NULL,'bottom','dress','balletcore'),
('rose_leotard','Rose Leotard','A comfortable practice leotard.','ballet','leotards','uncommon',160,40,NULL,'top','dress','balletcore,pink'),
('warmup_legwarmers','Warm-up Legwarmers','Soft legwarmers for practice.','ballet','warmups','common',70,90,NULL,'accessory','','balletcore,cozy'),
('ballet_practice_flats','Ballet Practice Flats','Flexible flats for rehearsals.','ballet','flats','common',125,80,NULL,'shoes','','balletcore'),
('pearl_pointe_shoes','Pearl Pointe Shoes','A collectible pointe-shoe design.','ballet','pointe_shoes','rare',270,10,NULL,'shoes','','balletcore'),
('ballet_duffel','Ballet Duffel Bag','A roomy rehearsal bag.','ballet','bags','uncommon',140,35,NULL,'bag','','balletcore'),
('volleyball_team_jersey','Volleyball Team Jersey','A breathable practice jersey.','volleyball','jerseys','common',130,85,NULL,'top','dress','sporty'),
('volleyball_training_shorts','Volleyball Training Shorts','Comfortable shorts for court practice.','volleyball','shorts','common',95,90,NULL,'bottom','dress','sporty'),
('court_kneepads','Court Kneepads','Soft supportive kneepads.','volleyball','kneepads','common',80,90,NULL,'accessory','','sporty'),
('pink_court_shoes','Pink Court Shoes','Light shoes for quick movements.','volleyball','shoes','uncommon',180,35,NULL,'shoes','','sporty,pink'),
('volleyball_gear_bag','Volleyball Gear Bag','A practical team gear bag.','volleyball','bags','uncommon',145,35,NULL,'bag','','sporty'),
('cheer_practice_top','Cheer Practice Top','A light top for routines.','cheer','tops','common',105,85,NULL,'top','dress','cheer'),
('cheer_pleated_skirt','Cheer Pleated Skirt','A classic practice skirt.','cheer','skirts','common',115,85,NULL,'bottom','dress','cheer'),
('captain_cheer_bow','Captain Cheer Bow','A bold bow for performance day.','cheer','bows','rare',180,12,NULL,'hair_accessory','','cheer,bows'),
('white_cheer_shoes','White Cheer Shoes','Supportive routine shoes.','cheer','shoes','uncommon',175,35,NULL,'shoes','','cheer'),
('cheer_weekend_bag','Cheer Weekend Bag','Room for a complete practice kit.','cheer','bags','uncommon',145,35,NULL,'bag','','cheer'),
('practice_water','Practice Water','A single-use refreshment.','consumables','drinks','common',20,100,NULL,NULL,'','sporty'),
('strawberry_snack','Strawberry Snack','A single-use after-practice snack.','consumables','food','common',25,100,NULL,NULL,'','strawberry'),
('practice_energy_bar','Practice Energy Bar','A single-use activity snack.','consumables','food','uncommon',40,35,NULL,NULL,'','sporty'),
('silver_team_pin','Silver Team Pin','A collectible team pin.','collectibles','pins','common',95,85,NULL,NULL,'','sporty'),
('tiny_ballet_figurine','Tiny Ballet Figurine','A small rehearsal keepsake.','collectibles','figurines','uncommon',175,35,NULL,NULL,'','balletcore'),
('glass_volleyball_trophy','Glass Volleyball Trophy','A rare court collectible.','collectibles','trophies','rare',400,10,NULL,NULL,'','sporty'),
('sparkle_cheer_pom','Sparkle Cheer Pom','A collectible performance pom.','collectibles','team','uncommon',160,35,NULL,NULL,'','cheer'),
('winter_velvet_bow','Winter Velvet Bow','A soft velvet holiday bow.','seasonal','hair_accessories','uncommon',120,35,'winter','hair_accessory','','winter,bows'),
('holiday_star_cardigan','Holiday Star Cardigan','A festive cozy cardigan.','seasonal','cardigans','rare',210,10,'christmas','outerwear','','christmas,cozy'),
('heart_day_charm','Heart Day Charm','A seasonal heart collectible.','seasonal','collectibles','rare',180,10,'valentines',NULL,'','hearts'),
('halloween_moon_bag','Halloween Moon Bag','A moon-shaped seasonal bag.','seasonal','bags','rare',240,10,'halloween','bag','','halloween'),
('summer_cherry_sundress','Summer Cherry Sundress','A light cherry-print summer dress.','seasonal','dresses','uncommon',175,35,'summer','dress','top,bottom','summer,cherries'),
('spring_flower_clip','Spring Flower Clip','A fresh flower hair clip.','seasonal','hair_clips','common',55,85,'spring','hair_accessory','','spring'),
('autumn_cozy_scarf','Autumn Cozy Scarf','A soft scarf for cooler days.','seasonal','accessories','common',70,85,'autumn','accessory','','autumn,cozy')
) AS seed(id,name,description,category,subcategory,rarity,price,weight,season,slot,conflict,tags)
ON CONFLICT (item_id) DO NOTHING;
