-- Exact legacy tool/drop identifiers and durability for gated Elixir activity parity.
-- No existing catalog row, price, ownership or cooldown is overwritten.
INSERT INTO economy_v2_catalog_items
  (item_id,name,description,category,buy_price,sell_price,tool_slot,durability)
VALUES
  ('fishing_rod','Fishing Rod','A basic fishing rod.','tools',65,32,'rod',40),
  ('brom_pickaxe','Brom''s Pickaxe','A basic mining pickaxe.','tools',100,50,'pickaxe',40),
  ('axe','Axe','A basic woodcutting axe.','tools',100,50,'axe',35),
  ('comet_rod','Comet Rod','A crafted fishing rod.','rare',NULL,75,'rod',130),
  ('star_rod','Star Rod','A crafted fishing rod.','rare',NULL,125,'rod',170),
  ('moon_rod','Moon Rod','A rare fishing rod.','rare',NULL,400,'rod',200),
  ('sparkle_rod','Sparkle Rod','A sparkling fishing rod.','rare',NULL,400,'rod',300),
  ('hellfire_rod','Hellfire Rod','A top-tier fishing rod.','rare',NULL,7500,'rod',2500),
  ('comet_pickaxe','Comet Pickaxe','A crafted mining pickaxe.','rare',NULL,145,'pickaxe',180),
  ('star_pickaxe','Star Pickaxe','A crafted mining pickaxe.','rare',NULL,175,'pickaxe',220),
  ('shooting_star_pickaxe','Shooting Star Pickaxe','An upgraded pickaxe.','rare',NULL,260,'pickaxe',260),
  ('diamond_pickaxe','Diamond Pickaxe','A high-tier pickaxe.','rare',NULL,500,'pickaxe',420),
  ('moon_pickaxe','Moon Pickaxe','A rare mining pickaxe.','rare',NULL,500,'pickaxe',320),
  ('sparkle_pickaxe','Sparkle Pickaxe','A sparkling pickaxe.','rare',NULL,600,'pickaxe',450),
  ('hellfire_pickaxe','Hellfire Pickaxe','A top-tier pickaxe.','rare',NULL,7500,'pickaxe',3000),
  ('comet_axe','Comet Axe','A crafted axe.','rare',NULL,145,'axe',170),
  ('star_axe','Star Axe','A crafted axe.','rare',NULL,175,'axe',220),
  ('moon_axe','Moon Axe','A rare axe.','rare',NULL,500,'axe',350),
  ('sparkle_axe','Sparkle Axe','A sparkling axe.','rare',NULL,600,'axe',500),
  ('hellfire_axe','Hellfire Axe','A top-tier axe.','rare',NULL,7500,'axe',3100),
  ('fish','Fish','A common catch.','drops',NULL,10,NULL,NULL),
  ('tropical_fish','Tropical Fish','A colorful catch.','drops',NULL,30,NULL,NULL),
  ('blowfish','Blowfish','A prickly catch.','drops',NULL,15,NULL,NULL),
  ('shell','Shell','A rare seaside find.','drops',NULL,800,NULL,NULL),
  ('shark','Shark','A rare catch.','drops',NULL,1000,NULL,NULL),
  ('crab','Crab','A seaside catch.','drops',NULL,40,NULL,NULL),
  ('squid','Squid','A deep-water catch.','drops',NULL,45,NULL,NULL),
  ('rock','Rock','A common mining find.','drops',NULL,5,NULL,NULL),
  ('cobweb','Cobweb','A mining material.','drops',NULL,10,NULL,NULL),
  ('gem_fragment','Gem Fragment','A crafting material.','drops',NULL,50,NULL,NULL),
  ('moon_rune','Moon Rune','A rare crafting material.','drops',NULL,100,NULL,NULL),
  ('sparkle_fragment','Sparkle Fragment','A rare crafting material.','drops',NULL,605,NULL,NULL),
  ('wood','Wood','A common woodcutting find.','drops',NULL,10,NULL,NULL),
  ('apple','Apple','A fruit from a tree.','drops',NULL,15,NULL,NULL),
  ('pear','Pear','A fruit from a tree.','drops',NULL,15,NULL,NULL),
  ('leaves','Leaves','A woodcutting material.','drops',NULL,5,NULL,NULL),
  ('fish_crate','Fish Treasure','A fishing treasure.','drops',NULL,100,NULL,NULL),
  ('mine_crate','Gem Crate','A mining treasure.','drops',NULL,100,NULL,NULL),
  ('chop_crate','Chop Crate','A woodcutting treasure.','drops',NULL,100,NULL,NULL)
ON CONFLICT (item_id) DO NOTHING;
